language: php

php:
  - 5.6

before_install:
  - echo "Running BeforeInstall"

before_script:
  - echo "Running BeforeScript"
  - composer self-update
  - composer install --no-interaction

script:
  - echo "RunningScript"
  - ./bin/kahlan --coverage=4 --clover=clover.xml

after_success:
  - echo "Running AfterSuccess"

after_script:
  - echo "Running AfterScript"
  - php ./bin/codacycoverage clover clover.xml -vvv

# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
  fast_finish: true

# Customize when the notification emails are sent.
notifications:
    on_success: never
    on_failure: never

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
